### ISSUE TITLE
IRPMon: not connected

### ISSUE THREAD

**Issue by romanholidaypancakes** [MartinDrab/IRPMon#100] opened 2021-03-12 08:24 UTC
how can I use it to make it work

![image](https://user-images.githubusercontent.com/51652878/110912724-3c2a6b00-834f-11eb-9b2e-c40e699c7ebb.png)

version: [v1.0-rc2](https://github.com/MartinDrab/IRPMon/releases/tag/v1.0-rc2)
os: win10 x64 18363

**Comment by MartinDrab** [comment] 2021-03-12 10:54
Hello,

did you run the program as administrator?

Checking the **Monitoring | Capture events** should connect to the driver.

Also, you may look at this tutorial
[Keyboard Monitoring](https://github.com/MartinDrab/IRPMon/wiki/KeyboardMonitoring)

I hope to release new version during this weekend.

**Comment by romanholidaypancakes** [comment] 2021-03-12 11:08
i follow this steps:
1. (run it on administrator)none - ok
![image](https://user-images.githubusercontent.com/51652878/110932161-1197dc80-8366-11eb-8c9f-5a166e63afb8.png)

2. gui
![image](https://user-images.githubusercontent.com/51652878/110932271-368c4f80-8366-11eb-9297-6264010ac023.png)

**Comment by MartinDrab** [comment] 2021-03-12 11:17
It seems the driver is not loaded.

Do you have Secure Boot disabled? Unfortunately, I am currently not able to make the driver load when the Secure Boot is enabled (I do not own necessary EV certificate yet).

**Comment by romanholidaypancakes** [comment] 2021-03-12 11:19
i run it on virtual machine. It should not have a secure boot by default.

![image](https://user-images.githubusercontent.com/51652878/110933825-33925e80-8368-11eb-9bec-f7986c409ddc.png)

**Comment by romanholidaypancakes** [comment] 2021-03-12 11:21
i wanna monitor all driver irp code then i need know who(application) connected it.

**Comment by MartinDrab** [comment] 2021-03-12 11:31
Well, I tried to connect to the driver and all seems to be OK. I did the following:
- I downloaded the [v1.0 RC2 release](https://github.com/MartinDrab/IRPMon/releases/tag/v1.0-rc2), the installer,
- I installed the program (with *Run IRPMon server on startup* unchecked),
- I run the program as administrator,
- in the **Connect to the driver** window, I selected **Device** and pressed **Ok**,
- now, I can connect to the driver via **Monitoring | Capture events**.

Since I have 64-bit version of Windows, I run 64-bit version of IRPMon (be careful with that since both versions are installed).

**Comment by romanholidaypancakes** [comment] 2021-03-12 11:43
- step 1
![image](https://user-images.githubusercontent.com/51652878/110935511-76edcc80-836a-11eb-87d6-6122419430ba.png)
- step 2
![image](https://user-images.githubusercontent.com/51652878/110935524-7ead7100-836a-11eb-93ec-e8fa55040900.png)
- step 3
![image](https://user-images.githubusercontent.com/51652878/110935554-8a009c80-836a-11eb-9b3c-7f3613e153cd.png)

- step 4:  (run` IRPMon 64-Bit` on administrator)none - ok

- still can't work

------
- new vmos: `winx64 10.0.17763.737`

**Comment by MartinDrab** [comment] 2021-03-12 16:13
Do not start the IRPMon server service (although it is strange because it seems it is not running anyway). The IRPMon application connects directly to the driver, not the server. The server may be used if you wish to have the GUI on machine other than the driver is... and it is quite unreliable.

**Comment by romanholidaypancakes** [comment] 2021-03-15 01:48
I changed step 3 to this, still not work
![image](https://user-images.githubusercontent.com/51652878/111093280-796f4280-8573-11eb-8ffe-2456468c6326.png)

**Comment by MartinDrab** [comment] 2021-03-15 20:24
Well, that all seems very strange. Can you provide me with a log from [Sysinternals DbgView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview)?

Run DbgView as administrator. You may do it before running the IRPMon installer. The following items need to be checked in the **Capture** menu:
- **Capture Win32**,
- **Capture Global Win32**,
- **Capture Kernel**,
- **Enable verbose kernel output**,
- **Capture kernel**.

Before installing IRPMon, uninstall it first (it should have its entry in the Control Panel).

After you run the IRPMon 64-bit application as administrator and see the main window (where you should see the list view for displaying individual requests), you may save the debug log to a file and upload it either here, or send it to me via email (martin.drab@email.cz).

Alternatively, if the VM is not too big nad your internet connection is strong enough, you may upload it somewhere and I will attemt to reproduce your problem.

**Comment by romanholidaypancakes** [comment] 2021-03-16 02:06
[DESKTOP-VUKB1AQ.LOG](https://github.com/MartinDrab/IRPMon/files/6145569/DESKTOP-VUKB1AQ.LOG)

**Closed as completed** 2022-11-17 01:45 UTC
Labels: question, gui
